version: "3.9"
services:
    camhr-scraper:
      image: data_scraper_image:latest
      container_name: data_scraper_container
      env_file:
          - .env
      ports:
        - "8000:8000"
      volumes:
        - ./:/opt/app
      working_dir: /opt/app
      entrypoint: ["python", "main.py"]
      profiles: ["data_scraper"]