SELECT
    E.EMPLOYEE_ID,
    J.JOB_TITLE,
    D.DEPARTMENT_NAME,
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME,
    JH.START_DATE
FROM JOB_HISTORY JH
JOIN EMPLOYEES E 
    ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN JOBS J 
    ON JH.JOB_ID = J.JOB_ID
JOIN DEPARTMENTS D 
    ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID
    WHERE JH.START_DATE BETWEEN TO_DATE('1997-12-01', 'YYYY-MM-DD') AND TO_DATE('2020-12-12', 'YYYY-MM-DD');
