SELECT
    Z.EMPLOYEE_ID,
    Z.FIRST_NAME || ' ' || Z.LAST_NAME AS EMPLOYEE_NAME,
    J.JOB_TITLE,
    Z.COMMISSION_PCT,
    MAX(B.START_DATE) AS START_DATE,
    MAX(B.END_DATE) AS END_DATE
FROM EMPLOYEES Z
LEFT JOIN JOBS J
    ON Z.JOB_ID = J.JOB_ID
LEFT JOIN JOB_HISTORY B
    ON Z.EMPLOYEE_ID = B.EMPLOYEE_ID
WHERE Z.COMMISSION_PCT IS NOT NULL
    AND (B.START_DATE IS NOT NULL OR B.END_DATE IS NOT NULL)
    GROUP BY Z.EMPLOYEE_ID, Z.FIRST_NAME || ' ' || Z.LAST_NAME, J.JOB_TITLE, Z.COMMISSION_PCT
