SELECT
    A.FIRST_NAME || ' ' || A.LAST_NAME EMPLOYEE_NAME,
    D.COUNTRY_NAME,
    C.CITY
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
    ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
LEFT JOIN LOCATIONS C
    ON B.LOCATION_ID = C.LOCATION_ID
LEFT JOIN COUNTRIES D
    ON C.COUNTRY_ID = D.COUNTRY_ID
