WITH MANAGER_TABLE AS(
    SELECT DISTINCT
        AA.EMPLOYEE_ID MANAGER_ID,
        AA.FIRST_NAME || ' ' || AA.LAST_NAME MANAGER_NAME,
        AA.SALARY,
        AA.DEPARTMENT_ID
    FROM EMPLOYEES AA, EMPLOYEES BB
    WHERE AA.EMPLOYEE_ID = BB.MANAGER_ID
), MASTER_TABLE AS (
    SELECT DISTINCT
        A.MANAGER_ID,
        A.MANAGER_NAME,
        C.CITY,
        B.DEPARTMENT_NAME,
        A.SALARY
    FROM MANAGER_TABLE A
    LEFT JOIN DEPARTMENTS B
        ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
    LEFT JOIN LOCATIONS C
        ON B.LOCATION_ID = C.LOCATION_ID
), FINAL_TABLE AS (
    SELECT DISTINCT DEPARTMENT_NAME, MANAGER_NAME, CITY, SALARY FROM MASTER_TABLE AA
    WHERE AA.SALARY > (SELECT AVG(SALARY) AVG_SALARY FROM EMPLOYEES)
)

SELECT * FROM FINAL_TABLE
