WITH EM_TABLE AS (
  SELECT
    AA.EMPLOYEE_ID,
    AA.FIRST_NAME,
    AA.LAST_NAME,
    AA.JOB_ID
  FROM EMPLOYEES AA
  WHERE AA.SALARY > 12000
), EX_TABLE AS (
  SELECT
    BB.EMPLOYEE_ID,
    BB.JOB_ID,
    MONTHS_BETWEEN(BB.END_DATE, BB.START_DATE) / 12 AS EXPERIENCE
  FROM JOB_HISTORY BB
)

SELECT DISTINCT
  AA.FIRST_NAME,
  AA.LAST_NAME,
  BB.JOB_ID,
  FLOOR(BB.EXPERIENCE) EXPERIENCE
FROM EM_TABLE AA
LEFT JOIN EX_TABLE BB
  ON AA.EMPLOYEE_ID = BB.EMPLOYEE_ID
WHERE EXPERIENCE IS NOT NULL
