WITH MANAGER_TABLE AS (
  SELECT DISTINCT
    BB.EMPLOYEE_ID AS MANAGER_ID,
    BB.FIRST_NAME || ' ' || BB.LAST_NAME AS MANAGER_NAME,
    BB.DEPARTMENT_ID
  FROM EMPLOYEES AA
  JOIN EMPLOYEES BB ON AA.MANAGER_ID = BB.EMPLOYEE_ID
), MASTER_TABLE AS (
  SELECT DISTINCT
    A.MANAGER_ID,
    A.MANAGER_NAME,
    B.DEPARTMENT_NAME
  FROM MANAGER_TABLE A
  RIGHT JOIN DEPARTMENTS B
  ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
)
SELECT DEPARTMENT_NAME, MANAGER_NAME FROM MASTER_TABLE
WHERE LOWER(MANAGER_NAME) LIKE '%n'
