SELECT
    AA.DEPARTMENT_ID,
    BB.DEPARTMENT_NAME,
    AVG(AA.SALARY) AS AVG_SALARY,
    MIN(AA.SALARY) AS MIN_SALARY,
    MAX(AA.SALARY) AS MAX_SALARY,
    COUNT(CASE WHEN AA.COMMISSION_PCT IS NOT NULL THEN 1 END) AS COUNT_COMMISSION_PCT
FROM EMPLOYEES AA
INNER JOIN DEPARTMENTS BB
ON AA.DEPARTMENT_ID = BB.DEPARTMENT_ID
GROUP BY AA.DEPARTMENT_ID, BB.DEPARTMENT_NAME
